### ISSUE TITLE
curl显示connection refused

### ISSUE THREAD

**Issue by WuYuZh17** [ANA-Training-2024/student0#2]
在https作业中，完成代码后make后出现了四个文件，但是curl后显示connection refused，报错如图，请求解答，谢谢！
报错如图：

**Comment by WuYuZh17** [comment]
<img width="945" alt="image" src="https://github.com/user-attachments/assets/fc77af14-8c4d-41e9-b104-521459b8f21f">

**Comment by WuYuZh17** [comment]
不知道各位学长能否看到图片:(

**Comment by abdtyx** [comment]
If you are going to test your program, I suggest you use two terminals. You can run the httpserver in one terminal and `nc` in another one. Remember, you can only establish a connection when the httpserver is running. If it fails to run or is just killed while running, you cannot connect it anymore.
